### ISSUE TITLE
Export Sessions bug  

### ISSUE THREAD

**Issue by fedikhatib** [sienori/Tab-Session-Manager#1385]
## Short description
I have many saved sessions with so many tabs(+2000) , i tried to export all the session from the settings but nothing happens. 

## Steps to reproduce
just try to export all the sessions.

## Expected result
session are exoprted

## Actual result
nothing happens but the console output is 

`background.js:2 Uncaught (in promise) TypeError: Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function callback): Message length exceeded maximum allowed length.
    at background.js:2:382955
    at new Promise (<anonymous>)
    at f (background.js:2:382880)
    at Object.apply (background.js:2:380329)
    at gt (background.js:2:491770)
    at async mt (background.js:2:490151)`

## Platform information
* Platform (OS): windows 11
* Version of browser: Chrome 128
* Version of Tab Session Manager: 7.0.1

**Comment by imtrobin** [comment]
Same here.  It is still working with edge but not for Maxthon (chromium based)

**Comment by sienori** [comment]
Thank you for the report! There was an issue where sessions couldn't be exported when there are a large number of them. I will fix this and include it in the next update. https://github.com/sienori/Tab-Session-Manager/commit/5d2336d824398f09a3c60d735cb1ae8e11dba32a
